# this script takes the energy IDv3 tag from the file and copies it to the rating
# NOTE: There will probably be some caveats here - like what the scale of the energy tag in your library is
# Mine are all generated by mixed in key, so they are out of 10, but YMMV

import taglib
import argparse
import sqlite3
from pathlib import Path
from os.path import abspath, relpath

from engineutils.track import Track

db_con = sqlite3.connect("Database2/m.db")
cursor = db_con.cursor()
cursor.execute("SELECT id, path FROM Track ORDER BY id ASC;")

# load tracks into a format we can work with
tracks = []

for t in cursor.fetchall():
    tracks.append(Track(t[0], t[1]))

for t in tracks:
    try:
        with taglib.File(t.path) as s:
            energy = int(s.tags['ENERGYLEVEL'][0])
            t.energy = 20*(20*energy if energy % 2 == 0 else 20*(energy + 1))
    except:
        t.energy = 100